#database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/report3
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtp.gmail.com 
    port: 587
    username: ashokpanhalkar4567@gmail.com
    password: eppakytxmnvagbco
    properties:
       mail:
        smtp:
         auth: true
        starttls:
         enable: true
  
      






